replicaCount: 1

auth:
  username: securestay_admin
  # password is injected via set_sensitive in modules/rabbitmq/main.tf
  erlangCookie: "E332F52C546C70618E29498837ADACECABFBEB2051765AE4D62BE728CA171CB0"

persistence:
  enabled: false

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"  # INTERNAL ONLY — not internet-facing

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

metrics:
  enabled: true  # Pre-wired for future Prometheus integration
